### ISSUE TITLE
Mention OpenStreetMap/OSM copyright on the map

### ISSUE THREAD

**Issue by carstenhag** [emfcamp/buildmap#3]
Hey, there needs to be a `© OpenStreetMap-Mitwirkende` or `© OpenStreetMap contributors` string with link to the copyright page on the map.

See https://www.openstreetmap.org/copyright.

**Comment by russss** [comment]
Thanks - for the CCCamp map it looks like that actually got lost when we switched to using our own basemap tiles rather than MapTiler, because the mbtiles file didn't get the attribution baked in. And I didn't notice until now as I was quite busy :).

I'd almost be inclined to call this a bug in the [tilemaker](https://github.com/systemed/tilemaker) OpenMapTiles config. It's not strictly a bug in buildmap. 

If we decide to archive the CCCamp map I will fix this, otherwise it is likely to go away shortly.
